### ISSUE TITLE
dead link found

### ISSUE THREAD

**Issue by hannesdelbeke** [pyblish/apidocs#10]
![image](https://user-images.githubusercontent.com/3758308/136432777-80725103-426e-4f5d-b1bd-7cd6d3ebd152.png)

there is a dead link on https://api.pyblish.com/pyblish.api/contextplugin
not sure where it has to point too

**Comment by hannesdelbeke** [comment]
maybe to here? https://api.pyblish.com/pyblish.api/context

**Comment by mottosso** [comment]
Yes, that's it. Good find. I'm off on holiday until end of next week, will take a look at this then. Also welcome to make a PR.

**Comment by hannesdelbeke** [comment]
found a few more. seems to be a capitalisation issue. 
PR https://github.com/pyblish/apidocs/pull/11

**Comment by hannesdelbeke** [comment]
another dead link https://api.pyblish.com/pluginsystem

register plugin paths https://github.com/pyblish/api/tree/9d41e509649f2dfb91bc4d595aebabed2dc0512f/pages/register_plugin_path.md

**Comment by hannesdelbeke** [comment]
more dead links https://api.pyblish.com/pyblish.api/discover#mechanism
not sure where the register plugin path page went

**Comment by mottosso** [comment]
Merged, thanks @hannesdelbeke!
